/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DesignRouteImport } from './routes/design'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ETokenRouteImport } from './routes/e.$token'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as AuthRegistroRouteImport } from './routes/auth/registro'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedFamiliaRouteImport } from './routes/_authenticated/familia'
import { Route as AuthenticatedEmergenciaRouteImport } from './routes/_authenticated/emergencia'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedMedicamentosIndexRouteImport } from './routes/_authenticated/medicamentos.index'
import { Route as AuthenticatedDocumentosIndexRouteImport } from './routes/_authenticated/documentos.index'
import { Route as AuthenticatedAgendaIndexRouteImport } from './routes/_authenticated/agenda.index'
import { Route as AuthenticatedPacienteIdRouteImport } from './routes/_authenticated/paciente.$id'
import { Route as AuthenticatedOnboardingPrimeiraAcaoRouteImport } from './routes/_authenticated/onboarding/primeira-acao'
import { Route as AuthenticatedOnboardingFamiliarRouteImport } from './routes/_authenticated/onboarding/familiar'
import { Route as AuthenticatedOnboardingFamiliaRouteImport } from './routes/_authenticated/onboarding/familia'
import { Route as AuthenticatedOnboardingEmergenciaRouteImport } from './routes/_authenticated/onboarding/emergencia'
import { Route as AuthenticatedMedicamentosNovoRouteImport } from './routes/_authenticated/medicamentos.novo'
import { Route as AuthenticatedEventosNovoRouteImport } from './routes/_authenticated/eventos.novo'
import { Route as AuthenticatedDocumentosNovoRouteImport } from './routes/_authenticated/documentos.novo'
import { Route as AuthenticatedDocumentosIdRouteImport } from './routes/_authenticated/documentos.$id'
import { Route as AuthenticatedAgendaNovaRouteImport } from './routes/_authenticated/agenda.nova'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicHooksSendMedicationRemindersRouteImport } from './routes/api/public/hooks/send-medication-reminders'
import { Route as ApiPublicHooksDoseActionRouteImport } from './routes/api/public/hooks/dose-action'
import { Route as AuthenticatedMedicamentosIdEditarRouteImport } from './routes/_authenticated/medicamentos.$id.editar'
import { Route as AuthenticatedEventosIdEditarRouteImport } from './routes/_authenticated/eventos.$id.editar'
import { Route as AuthenticatedAgendaIdEditarRouteImport } from './routes/_authenticated/agenda.$id.editar'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ETokenRoute = ETokenRouteImport.update({
  id: '/e/$token',
  path: '/e/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegistroRoute = AuthRegistroRouteImport.update({
  id: '/auth/registro',
  path: '/auth/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamiliaRoute = AuthenticatedFamiliaRouteImport.update({
  id: '/familia',
  path: '/familia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmergenciaRoute = AuthenticatedEmergenciaRouteImport.update({
  id: '/emergencia',
  path: '/emergencia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMedicamentosIndexRoute =
  AuthenticatedMedicamentosIndexRouteImport.update({
    id: '/medicamentos/',
    path: '/medicamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentosIndexRoute =
  AuthenticatedDocumentosIndexRouteImport.update({
    id: '/documentos/',
    path: '/documentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendaIndexRoute =
  AuthenticatedAgendaIndexRouteImport.update({
    id: '/agenda/',
    path: '/agenda/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPacienteIdRoute = AuthenticatedPacienteIdRouteImport.update({
  id: '/paciente/$id',
  path: '/paciente/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingPrimeiraAcaoRoute =
  AuthenticatedOnboardingPrimeiraAcaoRouteImport.update({
    id: '/onboarding/primeira-acao',
    path: '/onboarding/primeira-acao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingFamiliarRoute =
  AuthenticatedOnboardingFamiliarRouteImport.update({
    id: '/onboarding/familiar',
    path: '/onboarding/familiar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingFamiliaRoute =
  AuthenticatedOnboardingFamiliaRouteImport.update({
    id: '/onboarding/familia',
    path: '/onboarding/familia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingEmergenciaRoute =
  AuthenticatedOnboardingEmergenciaRouteImport.update({
    id: '/onboarding/emergencia',
    path: '/onboarding/emergencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMedicamentosNovoRoute =
  AuthenticatedMedicamentosNovoRouteImport.update({
    id: '/medicamentos/novo',
    path: '/medicamentos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventosNovoRoute =
  AuthenticatedEventosNovoRouteImport.update({
    id: '/eventos/novo',
    path: '/eventos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentosNovoRoute =
  AuthenticatedDocumentosNovoRouteImport.update({
    id: '/documentos/novo',
    path: '/documentos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentosIdRoute =
  AuthenticatedDocumentosIdRouteImport.update({
    id: '/documentos/$id',
    path: '/documentos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendaNovaRoute = AuthenticatedAgendaNovaRouteImport.update({
  id: '/agenda/nova',
  path: '/agenda/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendMedicationRemindersRoute =
  ApiPublicHooksSendMedicationRemindersRouteImport.update({
    id: '/api/public/hooks/send-medication-reminders',
    path: '/api/public/hooks/send-medication-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDoseActionRoute =
  ApiPublicHooksDoseActionRouteImport.update({
    id: '/api/public/hooks/dose-action',
    path: '/api/public/hooks/dose-action',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMedicamentosIdEditarRoute =
  AuthenticatedMedicamentosIdEditarRouteImport.update({
    id: '/medicamentos/$id/editar',
    path: '/medicamentos/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventosIdEditarRoute =
  AuthenticatedEventosIdEditarRouteImport.update({
    id: '/eventos/$id/editar',
    path: '/eventos/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendaIdEditarRoute =
  AuthenticatedAgendaIdEditarRouteImport.update({
    id: '/agenda/$id/editar',
    path: '/agenda/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emergencia': typeof AuthenticatedEmergenciaRoute
  '/familia': typeof AuthenticatedFamiliaRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/registro': typeof AuthRegistroRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/e/$token': typeof ETokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/agenda/nova': typeof AuthenticatedAgendaNovaRoute
  '/documentos/$id': typeof AuthenticatedDocumentosIdRoute
  '/documentos/novo': typeof AuthenticatedDocumentosNovoRoute
  '/eventos/novo': typeof AuthenticatedEventosNovoRoute
  '/medicamentos/novo': typeof AuthenticatedMedicamentosNovoRoute
  '/onboarding/emergencia': typeof AuthenticatedOnboardingEmergenciaRoute
  '/onboarding/familia': typeof AuthenticatedOnboardingFamiliaRoute
  '/onboarding/familiar': typeof AuthenticatedOnboardingFamiliarRoute
  '/onboarding/primeira-acao': typeof AuthenticatedOnboardingPrimeiraAcaoRoute
  '/paciente/$id': typeof AuthenticatedPacienteIdRoute
  '/agenda/': typeof AuthenticatedAgendaIndexRoute
  '/documentos/': typeof AuthenticatedDocumentosIndexRoute
  '/medicamentos/': typeof AuthenticatedMedicamentosIndexRoute
  '/agenda/$id/editar': typeof AuthenticatedAgendaIdEditarRoute
  '/eventos/$id/editar': typeof AuthenticatedEventosIdEditarRoute
  '/medicamentos/$id/editar': typeof AuthenticatedMedicamentosIdEditarRoute
  '/api/public/hooks/dose-action': typeof ApiPublicHooksDoseActionRoute
  '/api/public/hooks/send-medication-reminders': typeof ApiPublicHooksSendMedicationRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emergencia': typeof AuthenticatedEmergenciaRoute
  '/familia': typeof AuthenticatedFamiliaRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/registro': typeof AuthRegistroRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/e/$token': typeof ETokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/agenda/nova': typeof AuthenticatedAgendaNovaRoute
  '/documentos/$id': typeof AuthenticatedDocumentosIdRoute
  '/documentos/novo': typeof AuthenticatedDocumentosNovoRoute
  '/eventos/novo': typeof AuthenticatedEventosNovoRoute
  '/medicamentos/novo': typeof AuthenticatedMedicamentosNovoRoute
  '/onboarding/emergencia': typeof AuthenticatedOnboardingEmergenciaRoute
  '/onboarding/familia': typeof AuthenticatedOnboardingFamiliaRoute
  '/onboarding/familiar': typeof AuthenticatedOnboardingFamiliarRoute
  '/onboarding/primeira-acao': typeof AuthenticatedOnboardingPrimeiraAcaoRoute
  '/paciente/$id': typeof AuthenticatedPacienteIdRoute
  '/agenda': typeof AuthenticatedAgendaIndexRoute
  '/documentos': typeof AuthenticatedDocumentosIndexRoute
  '/medicamentos': typeof AuthenticatedMedicamentosIndexRoute
  '/agenda/$id/editar': typeof AuthenticatedAgendaIdEditarRoute
  '/eventos/$id/editar': typeof AuthenticatedEventosIdEditarRoute
  '/medicamentos/$id/editar': typeof AuthenticatedMedicamentosIdEditarRoute
  '/api/public/hooks/dose-action': typeof ApiPublicHooksDoseActionRoute
  '/api/public/hooks/send-medication-reminders': typeof ApiPublicHooksSendMedicationRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/design': typeof DesignRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/emergencia': typeof AuthenticatedEmergenciaRoute
  '/_authenticated/familia': typeof AuthenticatedFamiliaRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/registro': typeof AuthRegistroRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/e/$token': typeof ETokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/agenda/nova': typeof AuthenticatedAgendaNovaRoute
  '/_authenticated/documentos/$id': typeof AuthenticatedDocumentosIdRoute
  '/_authenticated/documentos/novo': typeof AuthenticatedDocumentosNovoRoute
  '/_authenticated/eventos/novo': typeof AuthenticatedEventosNovoRoute
  '/_authenticated/medicamentos/novo': typeof AuthenticatedMedicamentosNovoRoute
  '/_authenticated/onboarding/emergencia': typeof AuthenticatedOnboardingEmergenciaRoute
  '/_authenticated/onboarding/familia': typeof AuthenticatedOnboardingFamiliaRoute
  '/_authenticated/onboarding/familiar': typeof AuthenticatedOnboardingFamiliarRoute
  '/_authenticated/onboarding/primeira-acao': typeof AuthenticatedOnboardingPrimeiraAcaoRoute
  '/_authenticated/paciente/$id': typeof AuthenticatedPacienteIdRoute
  '/_authenticated/agenda/': typeof AuthenticatedAgendaIndexRoute
  '/_authenticated/documentos/': typeof AuthenticatedDocumentosIndexRoute
  '/_authenticated/medicamentos/': typeof AuthenticatedMedicamentosIndexRoute
  '/_authenticated/agenda/$id/editar': typeof AuthenticatedAgendaIdEditarRoute
  '/_authenticated/eventos/$id/editar': typeof AuthenticatedEventosIdEditarRoute
  '/_authenticated/medicamentos/$id/editar': typeof AuthenticatedMedicamentosIdEditarRoute
  '/api/public/hooks/dose-action': typeof ApiPublicHooksDoseActionRoute
  '/api/public/hooks/send-medication-reminders': typeof ApiPublicHooksSendMedicationRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/emergencia'
    | '/familia'
    | '/historico'
    | '/perfil'
    | '/auth/login'
    | '/auth/registro'
    | '/convite/$token'
    | '/e/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/agenda/nova'
    | '/documentos/$id'
    | '/documentos/novo'
    | '/eventos/novo'
    | '/medicamentos/novo'
    | '/onboarding/emergencia'
    | '/onboarding/familia'
    | '/onboarding/familiar'
    | '/onboarding/primeira-acao'
    | '/paciente/$id'
    | '/agenda/'
    | '/documentos/'
    | '/medicamentos/'
    | '/agenda/$id/editar'
    | '/eventos/$id/editar'
    | '/medicamentos/$id/editar'
    | '/api/public/hooks/dose-action'
    | '/api/public/hooks/send-medication-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/emergencia'
    | '/familia'
    | '/historico'
    | '/perfil'
    | '/auth/login'
    | '/auth/registro'
    | '/convite/$token'
    | '/e/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/agenda/nova'
    | '/documentos/$id'
    | '/documentos/novo'
    | '/eventos/novo'
    | '/medicamentos/novo'
    | '/onboarding/emergencia'
    | '/onboarding/familia'
    | '/onboarding/familiar'
    | '/onboarding/primeira-acao'
    | '/paciente/$id'
    | '/agenda'
    | '/documentos'
    | '/medicamentos'
    | '/agenda/$id/editar'
    | '/eventos/$id/editar'
    | '/medicamentos/$id/editar'
    | '/api/public/hooks/dose-action'
    | '/api/public/hooks/send-medication-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/design'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/dashboard'
    | '/_authenticated/emergencia'
    | '/_authenticated/familia'
    | '/_authenticated/historico'
    | '/_authenticated/perfil'
    | '/auth/login'
    | '/auth/registro'
    | '/convite/$token'
    | '/e/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/agenda/nova'
    | '/_authenticated/documentos/$id'
    | '/_authenticated/documentos/novo'
    | '/_authenticated/eventos/novo'
    | '/_authenticated/medicamentos/novo'
    | '/_authenticated/onboarding/emergencia'
    | '/_authenticated/onboarding/familia'
    | '/_authenticated/onboarding/familiar'
    | '/_authenticated/onboarding/primeira-acao'
    | '/_authenticated/paciente/$id'
    | '/_authenticated/agenda/'
    | '/_authenticated/documentos/'
    | '/_authenticated/medicamentos/'
    | '/_authenticated/agenda/$id/editar'
    | '/_authenticated/eventos/$id/editar'
    | '/_authenticated/medicamentos/$id/editar'
    | '/api/public/hooks/dose-action'
    | '/api/public/hooks/send-medication-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DesignRoute: typeof DesignRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegistroRoute: typeof AuthRegistroRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  ETokenRoute: typeof ETokenRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksDoseActionRoute: typeof ApiPublicHooksDoseActionRoute
  ApiPublicHooksSendMedicationRemindersRoute: typeof ApiPublicHooksSendMedicationRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$token': {
      id: '/e/$token'
      path: '/e/$token'
      fullPath: '/e/$token'
      preLoaderRoute: typeof ETokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/registro': {
      id: '/auth/registro'
      path: '/auth/registro'
      fullPath: '/auth/registro'
      preLoaderRoute: typeof AuthRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/familia': {
      id: '/_authenticated/familia'
      path: '/familia'
      fullPath: '/familia'
      preLoaderRoute: typeof AuthenticatedFamiliaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emergencia': {
      id: '/_authenticated/emergencia'
      path: '/emergencia'
      fullPath: '/emergencia'
      preLoaderRoute: typeof AuthenticatedEmergenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/medicamentos/': {
      id: '/_authenticated/medicamentos/'
      path: '/medicamentos'
      fullPath: '/medicamentos/'
      preLoaderRoute: typeof AuthenticatedMedicamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos/': {
      id: '/_authenticated/documentos/'
      path: '/documentos'
      fullPath: '/documentos/'
      preLoaderRoute: typeof AuthenticatedDocumentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda/': {
      id: '/_authenticated/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AuthenticatedAgendaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paciente/$id': {
      id: '/_authenticated/paciente/$id'
      path: '/paciente/$id'
      fullPath: '/paciente/$id'
      preLoaderRoute: typeof AuthenticatedPacienteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/primeira-acao': {
      id: '/_authenticated/onboarding/primeira-acao'
      path: '/onboarding/primeira-acao'
      fullPath: '/onboarding/primeira-acao'
      preLoaderRoute: typeof AuthenticatedOnboardingPrimeiraAcaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/familiar': {
      id: '/_authenticated/onboarding/familiar'
      path: '/onboarding/familiar'
      fullPath: '/onboarding/familiar'
      preLoaderRoute: typeof AuthenticatedOnboardingFamiliarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/familia': {
      id: '/_authenticated/onboarding/familia'
      path: '/onboarding/familia'
      fullPath: '/onboarding/familia'
      preLoaderRoute: typeof AuthenticatedOnboardingFamiliaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/emergencia': {
      id: '/_authenticated/onboarding/emergencia'
      path: '/onboarding/emergencia'
      fullPath: '/onboarding/emergencia'
      preLoaderRoute: typeof AuthenticatedOnboardingEmergenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medicamentos/novo': {
      id: '/_authenticated/medicamentos/novo'
      path: '/medicamentos/novo'
      fullPath: '/medicamentos/novo'
      preLoaderRoute: typeof AuthenticatedMedicamentosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos/novo': {
      id: '/_authenticated/eventos/novo'
      path: '/eventos/novo'
      fullPath: '/eventos/novo'
      preLoaderRoute: typeof AuthenticatedEventosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos/novo': {
      id: '/_authenticated/documentos/novo'
      path: '/documentos/novo'
      fullPath: '/documentos/novo'
      preLoaderRoute: typeof AuthenticatedDocumentosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos/$id': {
      id: '/_authenticated/documentos/$id'
      path: '/documentos/$id'
      fullPath: '/documentos/$id'
      preLoaderRoute: typeof AuthenticatedDocumentosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda/nova': {
      id: '/_authenticated/agenda/nova'
      path: '/agenda/nova'
      fullPath: '/agenda/nova'
      preLoaderRoute: typeof AuthenticatedAgendaNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-medication-reminders': {
      id: '/api/public/hooks/send-medication-reminders'
      path: '/api/public/hooks/send-medication-reminders'
      fullPath: '/api/public/hooks/send-medication-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendMedicationRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dose-action': {
      id: '/api/public/hooks/dose-action'
      path: '/api/public/hooks/dose-action'
      fullPath: '/api/public/hooks/dose-action'
      preLoaderRoute: typeof ApiPublicHooksDoseActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/medicamentos/$id/editar': {
      id: '/_authenticated/medicamentos/$id/editar'
      path: '/medicamentos/$id/editar'
      fullPath: '/medicamentos/$id/editar'
      preLoaderRoute: typeof AuthenticatedMedicamentosIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos/$id/editar': {
      id: '/_authenticated/eventos/$id/editar'
      path: '/eventos/$id/editar'
      fullPath: '/eventos/$id/editar'
      preLoaderRoute: typeof AuthenticatedEventosIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda/$id/editar': {
      id: '/_authenticated/agenda/$id/editar'
      path: '/agenda/$id/editar'
      fullPath: '/agenda/$id/editar'
      preLoaderRoute: typeof AuthenticatedAgendaIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmergenciaRoute: typeof AuthenticatedEmergenciaRoute
  AuthenticatedFamiliaRoute: typeof AuthenticatedFamiliaRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedAgendaNovaRoute: typeof AuthenticatedAgendaNovaRoute
  AuthenticatedDocumentosIdRoute: typeof AuthenticatedDocumentosIdRoute
  AuthenticatedDocumentosNovoRoute: typeof AuthenticatedDocumentosNovoRoute
  AuthenticatedEventosNovoRoute: typeof AuthenticatedEventosNovoRoute
  AuthenticatedMedicamentosNovoRoute: typeof AuthenticatedMedicamentosNovoRoute
  AuthenticatedOnboardingEmergenciaRoute: typeof AuthenticatedOnboardingEmergenciaRoute
  AuthenticatedOnboardingFamiliaRoute: typeof AuthenticatedOnboardingFamiliaRoute
  AuthenticatedOnboardingFamiliarRoute: typeof AuthenticatedOnboardingFamiliarRoute
  AuthenticatedOnboardingPrimeiraAcaoRoute: typeof AuthenticatedOnboardingPrimeiraAcaoRoute
  AuthenticatedPacienteIdRoute: typeof AuthenticatedPacienteIdRoute
  AuthenticatedAgendaIndexRoute: typeof AuthenticatedAgendaIndexRoute
  AuthenticatedDocumentosIndexRoute: typeof AuthenticatedDocumentosIndexRoute
  AuthenticatedMedicamentosIndexRoute: typeof AuthenticatedMedicamentosIndexRoute
  AuthenticatedAgendaIdEditarRoute: typeof AuthenticatedAgendaIdEditarRoute
  AuthenticatedEventosIdEditarRoute: typeof AuthenticatedEventosIdEditarRoute
  AuthenticatedMedicamentosIdEditarRoute: typeof AuthenticatedMedicamentosIdEditarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmergenciaRoute: AuthenticatedEmergenciaRoute,
  AuthenticatedFamiliaRoute: AuthenticatedFamiliaRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedAgendaNovaRoute: AuthenticatedAgendaNovaRoute,
  AuthenticatedDocumentosIdRoute: AuthenticatedDocumentosIdRoute,
  AuthenticatedDocumentosNovoRoute: AuthenticatedDocumentosNovoRoute,
  AuthenticatedEventosNovoRoute: AuthenticatedEventosNovoRoute,
  AuthenticatedMedicamentosNovoRoute: AuthenticatedMedicamentosNovoRoute,
  AuthenticatedOnboardingEmergenciaRoute:
    AuthenticatedOnboardingEmergenciaRoute,
  AuthenticatedOnboardingFamiliaRoute: AuthenticatedOnboardingFamiliaRoute,
  AuthenticatedOnboardingFamiliarRoute: AuthenticatedOnboardingFamiliarRoute,
  AuthenticatedOnboardingPrimeiraAcaoRoute:
    AuthenticatedOnboardingPrimeiraAcaoRoute,
  AuthenticatedPacienteIdRoute: AuthenticatedPacienteIdRoute,
  AuthenticatedAgendaIndexRoute: AuthenticatedAgendaIndexRoute,
  AuthenticatedDocumentosIndexRoute: AuthenticatedDocumentosIndexRoute,
  AuthenticatedMedicamentosIndexRoute: AuthenticatedMedicamentosIndexRoute,
  AuthenticatedAgendaIdEditarRoute: AuthenticatedAgendaIdEditarRoute,
  AuthenticatedEventosIdEditarRoute: AuthenticatedEventosIdEditarRoute,
  AuthenticatedMedicamentosIdEditarRoute:
    AuthenticatedMedicamentosIdEditarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DesignRoute: DesignRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegistroRoute: AuthRegistroRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  ETokenRoute: ETokenRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksDoseActionRoute: ApiPublicHooksDoseActionRoute,
  ApiPublicHooksSendMedicationRemindersRoute:
    ApiPublicHooksSendMedicationRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
